#!/usr/bin/env bash
set -eu

echo "Creating /etc/nix/nix.conf for binary cache configuration. sudo required."
mkdir -p /etc/nix
echo "binary-caches = https://cache.nixos.org/ https://nixcache.reflex-frp.org/" | tee -a /etc/nix/nix.conf 
