#!/usr/bin/env bash
set -eu

# curl https://nixos.org/nix/install | sh
curl -o install-2.0 https://raw.githubusercontent.com/NixOS/nixos-homepage/master/nix/install-2.0
chmod +x install-2.0
sh ./install-2.0

echo "Creating /etc/nix/nix.conf for binary cache configuration. sudo required."
sudo mkdir -p /etc/nix
echo "binary-caches = https://cache.nixos.org/ https://nixcache.reflex-frp.org/" | sudo tee -a /etc/nix/nix.conf 
