#!/bin/bash -e

top=${1:-$HOME}
yasm=1.3.0
lame=3.99.5
fdkaac=0.1.5
x264=stable
ffmpeg=2.8.x
env=$top/.databrary-transcoder

cd $top
if [[ ! -f $env ]] ; then
	echo "This will build or update a remote transcoder environment in $PWD."
	read -p "Abort now or press enter to continue..."
	cat > $env << EOF
export PATH=$top/bin:\$PATH
export LD_LIBRARY_PATH=$top/lib:\$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$top/lib/pkgconfig:\$PKG_CONFIG_PATH
export CPPFLAGS="-I$top/include \$CPPFLAGS"
export LDFLAGS="-L$top/lib \$LDFLAGS"
EOF
	. $env
	echo "source $env" >> ~/.bashrc
fi

mkdir -p src
cd src

if [[ ! -d yasm-$yasm ]] ; then
	curl -L http://www.tortall.net/projects/yasm/releases/yasm-${yasm}.tar.gz | tar -xzf -
fi
cd yasm-$yasm
./configure --prefix=$top
make
make install
cd ..

if [[ ! -d lame-$lame ]] ; then
	curl -L http://sourceforge.net/projects/lame/files/lame/3.99/lame-${lame}.tar.gz | tar -xzf-
fi
cd lame-${lame}
./configure --prefix=$top
make
make install
cd ..

if [[ ! -d fdk-aac-$fdkaac ]] ; then
	curl -L http://sourceforge.net/projects/opencore-amr/files/fdk-aac/fdk-aac-${fdkaac}.tar.gz | tar -xzf-
fi
cd fdk-aac-${fdkaac}
./configure --prefix=$top
make
make install
cd ..

if [[ ! -d x264 ]] ; then
	git clone -b $x264 git://git.videolan.org/x264.git
fi
cd x264
git checkout $x264
git pull
./configure --prefix=$top --enable-shared --disable-lavf
make
make install
cd ..

if [[ ! -d ffmpeg ]] ; then
	git clone git://source.ffmpeg.org/ffmpeg.git
fi
cd ffmpeg
git remote update origin
if [[ $ffmpeg = *.x ]] ; then
	ffmpeg=`git describe --abbrev=0 origin/release/${ffmpeg%.x}`
	ffmpeg=${ffmpeg#u}
	echo "Using ffmpeg $ffmpeg"
fi
git checkout $ffmpeg
./configure --prefix=$top --enable-gpl --enable-version3 --enable-nonfree --enable-libx264 --enable-libfdk-aac --enable-libmp3lame # --extra-ldexeflags='-lcr_run -u cr_run_link_me'
make
make install
cd ..
